export const APP_PATHS = {
  HOME: '/',
  LOGIN: '/portal-master/login',
  ARTICLES: '/articles',
  ARTICLE_DETAIL: '/articles/:slug',
  AUTHOR_DETAIL: '/authors/:slug',
  SNIPPETS: '/snippets',
  SNIPPET_DETAIL: '/snippets/:slug',
  DEVTOOLS: '/devtools',
  ERRORS: '/errors',
  ERROR_DETAIL: '/errors/:slug',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  ADMIN: '/portal-master',
  ADMIN_ARTICLES: '/portal-master/articles',
  ADMIN_ARTICLE_NEW: '/portal-master/articles/new',
  ADMIN_ARTICLE_EDIT: '/portal-master/articles/:id/edit',
  ADMIN_SNIPPETS: '/portal-master/snippets',
  ADMIN_SNIPPET_NEW: '/portal-master/snippets/new',
  ADMIN_SNIPPET_EDIT: '/portal-master/snippets/:id/edit',
  ADMIN_ERRORS: '/portal-master/errors',
  ADMIN_ERROR_NEW: '/portal-master/errors/new',
  ADMIN_ERROR_EDIT: '/portal-master/errors/:id/edit',
  ADMIN_REVIEW_QUEUE: '/portal-master/articles/review',
  ADMIN_WRITERS: '/portal-master/writers',
  ADMIN_WRITER_PERFORMANCE: '/portal-master/writers/:id',
  ADMIN_ASSIGNMENTS: '/portal-master/writers/assignments',
  ADMIN_WRITER_APPLICATIONS: '/portal-master/writer-applications',
  ADMIN_NOTIFICATIONS: '/portal-master/notifications',
  WRITER_PORTAL: '/writer-portal',
  WRITER_PORTAL_PROFILE: '/writer-portal/profile',
  WRITER_PORTAL_ASSIGNMENTS: '/writer-portal/assignments',
  WRITER_PORTAL_NOTIFICATIONS: '/writer-portal/notifications',
  WRITER_PORTAL_LOGIN: '/writer-portal/login',
  WRITER_PORTAL_REGISTER: '/writer-portal/register',
  WRITER_PORTAL_APPLY: '/writer-portal/apply',
  WRITER_PORTAL_ARTICLES: '/writer-portal/articles',
  WRITER_PORTAL_ARTICLE_NEW: '/writer-portal/articles/new',
  WRITER_PORTAL_ARTICLE_EDIT: '/writer-portal/articles/:id/edit',
  // Backward compatibility aliases
  WRITER: '/writer-portal',
  WRITER_PROFILE: '/writer-portal/profile',
  WRITER_ASSIGNMENTS: '/writer-portal/assignments',
  WRITER_NOTIFICATIONS: '/writer-portal/notifications',
  WRITER_LOGIN: '/writer-portal/login',
  WRITER_REGISTER: '/writer-portal/register',
  WRITER_APPLY: '/writer-portal/apply',
  WRITER_ARTICLES: '/writer-portal/articles',
  WRITER_ARTICLE_NEW: '/writer-portal/articles/new',
  WRITER_ARTICLE_EDIT: '/writer-portal/articles/:id/edit',
};

export const API_ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  ARTICLES: '/articles',
  SNIPPETS: '/snippets',
  ERRORS: '/errors',
  SEARCH: '/search',
};

export const STORAGE_KEYS = {
  THEME: 'devatlas_theme',
};

export const THEMES = {
  LIGHT: 'light',
  DARK: 'dark',
};
